frinx-uniconfig/supported-devices.md
-incorrect heading styling fixed
-capitalization of NETCONF fixed
Signed-off by: Matej Matkuliak <mmatkuliak@frinx.io>
=> Supported devices fix

frinx-uniconfig/user-guide/uniconfig-operations/build-and-commit-model/readme.md
Signed-off-by: bmalo <bmalo@frinx.io>
@jaro0149 
@matkuliak
=> UNIC-624 Adding transaction idle timeout to configuration.

frinx-uniconfig/user-guide/uniconfig-operations/templates-manager/readme.md
- Ported documentation about manual setting of this parameter.
- Added doc about auto-configuration of this parameter based
on installed YANG repository and setting in the config file.
=> Added docuemntation for latest schema repository setting

frinx-uniconfig/user-guide/uniconfig-operations/restconf/readme.md
Signed-off-by: Peter Hlavaty <phlavaty@frinx.io>
=> Added leafref validation documentation

frinx-uniconfig/user-guide/uniconfig-operations/yang-patch/readme.md
Author: Jakub Boguščiak <jbogusciak@frinx.io>
=> Added documentation for YANG patch

frinx-uniconfig/user-guide/uniconfig-operations/index.md, frinx-uniconfig/user-guide/uniconfig-operations/utilities/index.md, frinx-uniconfig/user-guide/uniconfig-operations/utilities/yang-packager/readme.md
added:
- https://gerrit.frinx.io/c/Frinx-docs/+/11936
- https://gerrit.frinx.io/c/Frinx-docs/+/12056
=> YANG Packager docs

frinx-uniconfig/user-guide/operational-procedures/logging/readme.md, frinx-uniconfig/user-guide/uniconfig-operations/dryrun-manager/readme.md, frinx-uniconfig/user-guide/uniconfig-operations/snapshot-manager/rpc_create-snapshot/readme.md, frinx-uniconfig/user-guide/uniconfig-operations/snapshot-manager/rpc_replace-config-with-snapshot/readme.md, frinx-uniconfig/user-guide/uniconfig-operations/subtree-manager/rpc_calculate-subtree-diff/readme.md, frinx-uniconfig/user-guide/uniconfig-operations/subtree-manager/rpc_calculate-subtree-git-like-diff/readme.md, frinx-uniconfig/user-guide/uniconfig-operations/templates-manager/readme.md, frinx-uniconfig/user-guide/uniconfig-operations/transaction-log/rpc_revert-changes/readme.md, frinx-uniconfig/user-guide/uniconfig-operations/uniconfig-node-manager/rpc_calculate-diff/readme.md, frinx-uniconfig/user-guide/uniconfig-operations/uniconfig-node-manager/rpc_checked-commit/readme.md, frinx-uniconfig/user-guide/uniconfig-operations/uniconfig-node-manager/rpc_commit/readme.md, frinx-uniconfig/user-guide/uniconfig-operations/uniconfig-node-manager/rpc_is-in-sync/readme.md, frinx-uniconfig/user-guide/uniconfig-operations/uniconfig-node-manager/rpc_replace-config-with-oper/readme.md, frinx-uniconfig/user-guide/uniconfig-operations/uniconfig-node-manager/rpc_validate/readme.md
- https://gerrit.frinx.io/c/Frinx-docs/+/12248
=> UNIC-29 Separate errors to more types

frinx-uniconfig/user-guide/uniconfig-operations/yang-patch/readme.md
- https://gerrit.frinx.io/c/Frinx-docs/+/12255
=> Added documentation for rename operation inside YANG patch

frinx-uniconfig/user-guide/uniconfig-operations/restconf/readme.md
- https://gerrit.frinx.io/c/Frinx-docs/+/12348
=> UNIC-14 Documentation for 'insert' and 'point' query parameter

frinx-uniconfig/user-guide/operational-procedures/logging/readme.md
=> Added transactions to restconf audit logs

frinx-uniconfig/user-guide/operational-procedures/high-availability-cluster/readme.md
=> Information about sensitive data added

frinx-uniconfig/user-guide/uniconfig-operations/uniconfig-node-manager/rpc_calculate-diff/readme.md
Signed-off-by: Marek Pastorek <mpastorek@frinx.io>
=> Updated calculate-diff rpc output for reordered-lists

frinx-uniconfig/user-guide/network-management-protocols/uniconfig-installing/readme.md, frinx-uniconfig/user-guide/network-management-protocols/uniconfig_netconf/readme.md
=> Update documentation of max-(re)connection-attempts

frinx-uniconfig/user-guide/operational-procedures/logging/readme.md
=> Ignoring and logging of uknown configuration parameters

frinx-uniconfig/user-guide/uniconfig-operations/build-and-commit-model/readme.md, frinx-uniconfig/user-guide/uniconfig-operations/immediate-commit-model/readme.md
=> Turn off immediate commit

frinx-uniconfig/user-guide/uniconfig-operations/kafka-notifications/readme.md
Signed-off-by: Peter Hlavaty <phlavaty@frinx.io>
=> Added connect notification documentation

frinx-uniconfig/user-guide/uniconfig-operations/build-and-commit-model/readme.md
Signed-off-by: Peter Hlavaty <phlavaty@frinx.io>
=> Added configurable transaction timeout documentation

frinx-uniconfig/user-guide/network-management-protocols/updating-installation-parameters/readme.md
Signed-off-by: Marek Pastorek <mpastorek@frinx.io>
=> Udating installation parameters

frinx-uniconfig/user-guide/uniconfig-operations/uniconfig-node-manager/rpc_commit/readme.md
=> Commit rpc validate flag

frinx-uniconfig/user-guide/uniconfig-operations/templates-manager/readme.md
=> Upgrade-template RPC documentation

frinx-uniresource/pools/readme.md
Adding section where it is written how to create nested pool using Frinx UI
=> add section for nested pool in uniresource

frinx-machine/use-cases/create-l2-vpn-p2p/readme.md
=> l2vpn small fix

frinx-uniconfig/user-guide/uniconfig-operations/yang-patch/readme.md
=> Fixed yang patch headers

frinx-uniconfig/translation-units-docs/Translation framework 101.md
=> Update Translation framework 101.md

frinx-uniconfig/user-guide/uniconfig-operations/utilities/yang-packager/readme.md
@jaro0149 @matkuliak 
Signed-off-by: bmalo <bmalo@frinx.io>
=> Option to yang packager

frinx-uniconfig/translation-units-docs/configuration-datasets/acl/acl.md
DOC for completed acl options (multiple ports when eq or neq and new commands - option and precedence)
=> VZ-657 CPE13 name access-lists doc

frinx-uniconfig/user-guide/uniconfig-operations/utilities/yang-packager/readme.md
Adjusted a parameter in script.
=> Adjust parameters in script

frinx-uniconfig/translation-units-docs/configuration-datasets/acl/acl.md
DOC for VZ-662 Reconcile acl ios/ios xe TU issues. Solved established state for ios and ios xe.
=> VZ-662 DOC for Reconcile acl ios/ios xe TU issues

frinx-uniconfig/user-guide/uniconfig-operations/operational-data-about-transactions/readme.md
Signed-off-by: Peter Hlavaty <phlavaty@frinx.io>
=> Added documentation for data about transactions

frinx-uniconfig/translation-units-docs/configuration-datasets/interfaces/lag_interface.md
DOC for TASK: VZ-664 TU for vlan-untagged-data in LAG interface
=> VZ-664 TU for vlan-untagged-data in LAG interface

frinx-uniconfig/user-guide/uniconfig-operations/utilities/yang-packager/readme.md
- small formatting issue
Signed-off by: Matej Matkuliak <mmatkuliak@frinx.io>
=> Yang-packager fix

frinx-uniconfig/release-notes/index.md, frinx-uniconfig/release-notes/uniconfig-5.0.6.md
Signed-off by: Matej Matkuliak <mmatkuliak@frinx.io>
=> Release notes for 5.0.6

.github/workflows/retype.yml
- swapped retype build action from "v2" to "latest
- swapped the secret key for the PRO key we purchased
=> Update build action to latest

frinx-uniconfig/user-guide/network-management-protocols/uniconfig-installing/readme.md
Signed-off-by: marek pastorek <mpastorek@frinx.io>
=> Added netconf-node-topology:concurrent-rpc-limit parameter

frinx-machine/getting-started/readme.md
Signed-off-by: Simon Misencik <simon.misencik@gmail.com>
=> Add info about frinx-machine helm chart installation

frinx-uniconfig/user-guide/uniconfig-operations/restconf/readme.md
Signed-off-by: bmalo <bmalo@frinx.io>
=> Adding with-defaults query parameter.

frinx-uniconfig/release-notes/index.md, frinx-uniconfig/release-notes/uniconfig-5.0.7.md
=> 5.0.7 release notes

frinx-uniconfig/translation-units-docs/configuration-datasets/interfaces/ethernet_interface.md
Documentation for Ethernet interface's link-aggregate for CER devices.
=> CER interface UNIT - Ethernet interfaces

frinx-uniconfig/user-guide/uniconfig-operations/admin-state/readme.md
=> Added documentation for Admin-State

frinx-uniconfig/user-guide/uniconfig-operations/restconf/readme.md
Signed-off-by: bmalo <bmalo@frinx.io>
=> Added new setting for hide empty data nodes.

frinx-uniconfig/developer-guide/metrics/readme.md, frinx-uniconfig/user-guide/monitoring/readme.md
Add documentation for Metrics functionality
- User documentation
- Developer documentation
JIRA: UNIC-759
Signed-off-by: Peter Puškár <ppuskar@frinx.io>
=> Metrics documentation

frinx-uniconfig/user-guide/uniconfig-operations/restconf/readme.md
=> Updated default value of content query parameter

frinx-uniconfig/translation-units-docs/operational-datasets/platform.md
DOC for VZ-672 Collecting inventory
=> VZ-672 Collecting inventory DOC

frinx-uniconfig/user-guide/uniconfig-operations/admin-state/readme.md
Signed-off-by: Jakub Boguščiak <jbogusciak@frinx.io>
=> Add GET request for admin-state

frinx-uniconfig/translation-units-docs/configuration-datasets/interfaces/ethernet_interface.md
DOC for VZ-677 TUs for lacp port-priority on CBR8 devices.
=> VZ-677 Create TU for CBR8 - lacp port-priority DOC

frinx-uniconfig/user-guide/uniconfig-operations/restconf/readme.md
=> Updated doc: hide empty data nodes (RESTCONF)

frinx-uniconfig/user-guide/uniconfig-operations/restconf/readme.md
Signed-off-by: Adam Kuchcik <akuchcik@frinx.io>
=> Added unhide parameter for write operations

frinx-uniconfig/user-guide/network-management-protocols/uniconfig_cli/readme.md
=> Update execute-and-expect rpc doc

frinx-uniconfig/user-guide/uniconfig-operations/restconf/readme.md, frinx-uniconfig/user-guide/uniconfig-operations/uniconfig-shell/readme.md
Reviewer: @Jaroslav @marosmars 
Wait for code merge. VHD-141
=> Hide attributes query parameter

frinx-uniconfig/user-guide/operational-procedures/data-security-models/index.md
=> Added note about usage of encrypted-paths module

frinx-uniconfig/release-notes/update_release_notes.sh
- Added script needed for the automation of adding release notes
Signed-off-by: Adam Kuchcik <akuchcik@frinx.io>
=> Automation of adding release notes to documetation

.github/workflows/retype.yml
Signed-off-by: Adam Kuchcik <akuchcik@frinx.io>
=> Publish website when release notes are added

frinx-uniconfig/release-notes/index.md, frinx-uniconfig/release-notes/uniconfig-5.0.10.md, frinx-uniconfig/release-notes/uniconfig-5.0.11.md, frinx-uniconfig/release-notes/uniconfig-5.0.12.md, frinx-uniconfig/release-notes/uniconfig-5.0.13.md, frinx-uniconfig/release-notes/uniconfig-5.0.7.md, frinx-uniconfig/release-notes/uniconfig-5.0.8.md, frinx-uniconfig/release-notes/uniconfig-5.0.9.md
=> Add missing release notes

frinx-uniconfig/Q_A.md, frinx-uniconfig/user-guide/uniconfig-operations/uniconfig-node-manager/rpc_commit/readme.md
=> Add example of using do-rollback flag in commit

frinx-uniconfig/user-guide/operational-procedures/uniconfig-clustering/index.md, frinx-uniconfig/user-guide/uniconfig-operations/build-and-commit-model/readme.md
=> add maxInternalDbConnection into docs

frinx-uniconfig/user-guide/uniconfig-operations/restconf/readme.md
Added examples and explanation of usage patch request with apply-tags parameter
=> PATCH operation with apply-tags parameter

frinx-uniconfig/user-guide/operational-procedures/data-security-models/index.md
- Formatting of encrypted strings.
=> Updated encryption documentation

frinx-uniconfig/user-guide/uniconfig-operations/templates-manager/readme.md
=> Automatic upgrading of templates

frinx-uniconfig/user-guide/uniconfig-operations/restconf/readme.md, frinx-uniconfig/user-guide/uniconfig-operations/uniconfig-shell/readme.md
Signed-off-by: marek pastorek <mpastorek@frinx.io>
=> Documentation for callbacks

frinx-uniconfig/release-notes/index.md, frinx-uniconfig/release-notes/uniconfig-5.0.17.md
This reverts commit f3ba10d9accdbb6345130f30ce7eb27d0847544b.
=> Revert "Release 5.0.17 notes"

frinx-uniconfig/user-guide/uniconfig-operations/jsonb-filtering/application-jsonb-filtering/readme.md
@jaro0149 
Signed-off-by: Jakub Boguščiak <jbogusciak@frinx.io>
=> Add application JSONB filtering request example

frinx-uniconfig/user-guide/uniconfig-operations/jsonb-filtering/database-jsonb-filtering/readme.md
=> Fixed database filtering page title

frinx-uniconfig/user-guide/network-management-protocols/uniconfig_cli/readme.md
Signed-off-by: marek pastorek <mpastorek@frinx.io>
=> Documentation for config-coverage RPC

frinx-uniconfig/user-guide/network-management-protocols/uniconfig-installing/readme.md
Signed-off-by: Jakub Boguščiak <jbogusciak@frinx.io>
=> Add docs for new flag that stores failed installations into DB

frinx-uniconfig/translation-units-docs/operational-datasets/platform.md
- DOC for CER Arris platform on Arris CER devices
=> CER Arris Platform docs

frinx-uniconfig/user-guide/uniconfig-operations/uniconfig-node-manager/rpc_commit/readme.md
- add info block about this parameter
- add successful RPC example
JIRA: PANT-59
=> Docs for commit with skip unreachable nodes param

frinx-uniconfig/translation-units-docs/operational-datasets/platform.md
These changes seem to have been left out earlier, apologies
=> Copy check

frinx-uniconfig/user-guide/uniconfig-operations/uniconfig-node-manager/rpc_commit/readme.md
=> change overallStatus to fail when skippin unreachable nodes

frinx-uniconfig/user-guide/uniconfig-operations/build-and-commit-model/readme.md
- Optional parameter for changing response status code, if transaction is not valid or does not exists.
JIRA: UNIC-1071
TYPE: Improvement
Signed-off-by: Branislav Malo <bmalo@frinx.io>
=> Change status code if transaction is not valid.

frinx-uniconfig/getting-started.md
- Remove all license related code inside uniconfig.
JIRA: UNIC-972
TYPE: Improvement
Signed-off-by: Branislav Malo <bmalo@frinx.io>
=> Remove license server and token

frinx-uniconfig/translation-units-docs/operational-datasets/platform.md
=> VZ-724 Doc

frinx-uniconfig/translation-units-docs/operational-datasets/system.md
- Rewritten readers for System NTP for SAOS8 and SAOS6 devices DOC
- JIRA: VZ-739
=> DOC for VZ-739 - System NTP operational data readers

frinx-uniconfig/user-guide/uniconfig-operations/kafka-notifications/readme.md
- added topology-id to the DCE
=> Updated doc for DCE

frinx-uniconfig/translation-units-docs/configuration-datasets/aaa.md, frinx-uniconfig/translation-units-docs/configuration-datasets/relay-agent.md, frinx-uniconfig/translation-units-docs/operational-datasets/platform.md
- added Ciena related platform fields
- added Ciena related aaa field
- created Relay Agent docs for Ciena
=> Docs for missing attributes

frinx-uniconfig/user-guide/network-management-protocols/uniconfig_netconf/readme.md
- DOC for running Netconf test tool from docker image on Docker hub
JIRA: UNIC-1159
=> DOC for Netconf test tool docker image

frinx-uniconfig/user-guide/uniconfig-operations/subtree-manager/rpc_calculate-subtree-diff/RPC_calculate_subtree_diff-RPC_calculate_subtree_diff.svg, frinx-uniconfig/user-guide/uniconfig-operations/subtree-manager/rpc_calculate-subtree-diff/readme.md, frinx-uniconfig/user-guide/uniconfig-operations/subtree-manager/rpc_calculate-subtree-diff/subtree-diff-rpc.puml, frinx-uniconfig/user-guide/uniconfig-operations/subtree-manager/rpc_calculate-subtree-git-like-diff/RPC_calculate-subtree-git-like-diff-RPC_calculate_subtree_git_like_diff.svg, frinx-uniconfig/user-guide/uniconfig-operations/subtree-manager/rpc_calculate-subtree-git-like-diff/readme.md, frinx-uniconfig/user-guide/uniconfig-operations/subtree-manager/rpc_calculate-subtree-git-like-diff/subtree-git-like-diff-rpc.puml
- Reflecting API changes in UniConfig.
=> Updated calculate-subtree-diff RPC documentation

frinx-uniconfig/user-guide/performance-and-scale/performance_characteristics.md
Signed-off-by: Maros Marsalek <mmarsalek@frinx.io>
=> Performance characteristics

frinx-uniconfig/user-guide/network-management-protocols/uniconfig-installing/readme.md
- Description of new install parameters
JIRA: UNIC-1189
=> DOC for new install parameters

frinx-uniconfig/user-guide/network-management-protocols/uniconfig_netconf/readme.md
- reflecting latest changes done in the UniConfig service
- adding example about both adding / removing keys
- adding example how to read existing keys
=> Updated documentation about NETCONF keys

frinx-uniconfig/user-guide/uniconfig-operations/uniconfig-node-manager/uniconfig_check_installed_devices/readme.md, frinx-uniconfig/user-guide/uniconfig-operations/uniconfig-node-manager/uniconfig_get_installed_devices/readme.md, frinx-uniconfig/user-guide/uniconfig-operations/uniconfig-node-manager/uniconfig_install_multiple_nodes/readme.md, frinx-uniconfig/user-guide/uniconfig-operations/uniconfig-node-manager/uniconfig_uninstall_multiple_nodes/readme.md
JIRA: UNIC-1283
TYPE: API
@jaro0149 
@knuuzor 
Ready to be merged.
=> Refactor connection-manager RPCs

frinx-uniconfig/user-guide/uniconfig-operations/transaction-log/rpc_revert-changes/readme.md
Update revert-changes rpc docs
- Compliant with refactoring of revert-changes rpc and others.
=> Update revert-changes rpc docs

frinx-uniconfig/user-guide/uniconfig-operations/snapshot-manager/rpc_create-snapshot/readme.md, frinx-uniconfig/user-guide/uniconfig-operations/snapshot-manager/rpc_delete-snapshot/readme.md, frinx-uniconfig/user-guide/uniconfig-operations/snapshot-manager/rpc_replace-config-with-snapshot/readme.md
- Compliant with refactoring of snapshot-manager rpcs.
=> Update snapshot-manager rpc docs

frinx-uniconfig/release-notes/index.md, frinx-uniconfig/release-notes/uniconfig-5.1.14.md
This reverts commit e3a6817de0c0ad0c37da7100a85d87cea12a3ebf.
=> Revert "Release 5.1.14 notes"

frinx-uniconfig/release-notes/index.md
This reverts commit 1fc153a952d1c552eeff25eac871c028209d1e2e.
=> Revert "Release  notes"

frinx-uniconfig/user-guide/uniconfig-operations/subtree-manager/rpc_bulk-edit/readme.md, frinx-uniconfig/user-guide/uniconfig-operations/subtree-manager/rpc_calculate-subtree-diff/readme.md, frinx-uniconfig/user-guide/uniconfig-operations/subtree-manager/rpc_calculate-subtree-git-like-diff/readme.md, frinx-uniconfig/user-guide/uniconfig-operations/subtree-manager/rpc_copy-many-to-one/readme.md, frinx-uniconfig/user-guide/uniconfig-operations/subtree-manager/rpc_copy-one-to-many/readme.md, frinx-uniconfig/user-guide/uniconfig-operations/subtree-manager/rpc_copy-one-to-one/readme.md
=> Refactoring subtree manager RPCs

frinx-uniconfig/user-guide/monitoring/readme.md, frinx-uniconfig/user-guide/network-management-protocols/uniconfig-installing/readme.md, frinx-uniconfig/user-guide/operational-procedures/data-security-models/index.md, frinx-uniconfig/user-guide/operational-procedures/logging/readme.md, frinx-uniconfig/user-guide/operational-procedures/postgres-tls/readme.md, frinx-uniconfig/user-guide/operational-procedures/tls/readme.md, frinx-uniconfig/user-guide/operational-procedures/uniconfig-clustering/index.md, frinx-uniconfig/user-guide/operational-procedures/uniconfig-properties/readme.md, frinx-uniconfig/user-guide/uniconfig-operations/build-and-commit-model/readme.md, frinx-uniconfig/user-guide/uniconfig-operations/immediate-commit-model/readme.md, frinx-uniconfig/user-guide/uniconfig-operations/kafka-notifications/readme.md, frinx-uniconfig/user-guide/uniconfig-operations/restconf/readme.md, frinx-uniconfig/user-guide/uniconfig-operations/transaction-log/transaction-tracker/readme.md, frinx-uniconfig/user-guide/uniconfig-operations/uniconfig-shell/readme.md
Update old json config file to new application.properties format.
Add 2 new CLI Shell properties.
=> Update old json config file to new application.properties format.

frinx-uniconfig/user-guide/uniconfig-operations/uniconfig-properties/rpc_read-properties/readme.md, frinx-uniconfig/user-guide/uniconfig-operations/uniconfig-properties/rpc_update-properties/readme.md
=> Change "key" to "name" in update-properties RPC

frinx-uniconfig/user-guide/uniconfig-operations/uniconfig-node-manager/rpc_connect-node/readme.md, frinx-uniconfig/user-guide/uniconfig-operations/uniconfig-node-manager/rpc_disconnect-node/readme.md
Signed-off-by: Adam Kuchcik <adam.kuchcik@elisapolystar.com>
=> Fix connect/disconnect node RPCs

frinx-uniconfig/user-guide/uniconfig-operations/uniconfig-node-manager/rpc_health/readme.md
Updated the output for the health-check using the RPC implementation.
=> Fix healtcheck documentation.
